//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.HectorUav
{
    [Serializable]
    public class EnableMotorsRequest : Message
    {
        public const string k_RosMessageName = "hector_uav_msgs/EnableMotors";
        public override string RosMessageName => k_RosMessageName;

        public bool enable;
        //  enable or disable motors

        public EnableMotorsRequest()
        {
            this.enable = false;
        }

        public EnableMotorsRequest(bool enable)
        {
            this.enable = enable;
        }

        public static EnableMotorsRequest Deserialize(MessageDeserializer deserializer) => new EnableMotorsRequest(deserializer);

        private EnableMotorsRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.enable);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.enable);
        }

        public override string ToString()
        {
            return "EnableMotorsRequest: " +
            "\nenable: " + enable.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
