//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.HectorUav
{
    [Serializable]
    public class EnableMotorsResponse : Message
    {
        public const string k_RosMessageName = "hector_uav_msgs/EnableMotors";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        //  whether enabling or disabling was successful

        public EnableMotorsResponse()
        {
            this.success = false;
        }

        public EnableMotorsResponse(bool success)
        {
            this.success = success;
        }

        public static EnableMotorsResponse Deserialize(MessageDeserializer deserializer) => new EnableMotorsResponse(deserializer);

        private EnableMotorsResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "EnableMotorsResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
